# Generated by Django 3.2.9 on 2021-12-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211205_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='FirstName', max_length=20)),
                ('last_name', models.CharField(default='LastName', max_length=20)),
                ('birthday', models.DateTimeField()),
                ('address', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
