# Generated by Django 3.2.9 on 2021-12-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211205_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='start_work',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
