# Generated by Django 3.2.9 on 2021-12-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee_start_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='license_driver',
            field=models.CharField(default='Номер', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='license_driver_data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_information',
            field=models.CharField(default='Серія, номер, де і ким виданий', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default="Ім'я", max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Прізвище', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_work',
            field=models.DateField(auto_now=True),
        ),
    ]
