# Generated by Django 3.2.9 on 2021-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211205_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='license_driver_data',
            field=models.DateField(),
        ),
    ]
