# Generated by Django 3.2.9 on 2021-12-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_car', models.CharField(default='', max_length=20, verbose_name='Марка машини')),
                ('year_create', models.IntegerField(default=0, verbose_name='Рік виготовлення машини')),
                ('number_car', models.CharField(default='', max_length=20, verbose_name='Номерний знак машини')),
                ('type_fuel_engine', models.CharField(choices=[('disel', 'Дизель'), ('petrol', 'Бензин'), ('gas_petrol', 'Газ/бензин'), ('Electro', 'Електричний'), ('Petrol_electro', 'Бензин/електричний')], default='petrol', max_length=20, verbose_name='Тип двигуна')),
                ('kilometrage_car', models.IntegerField(default=0, verbose_name='Кілометраж')),
                ('photo_car', models.ImageField(upload_to=None, verbose_name='Фото машини')),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
