# Generated by Django 3.2.9 on 2021-12-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211209_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kilometrage_car',
            field=models.IntegerField(default=15, verbose_name='Кілометраж'),
        ),
    ]
