# Generated by Django 3.2.9 on 2021-12-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_kilometrage_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo_car',
            field=models.IntegerField(default=15, verbose_name='ВІнтаж'),
        ),
    ]
